
import java.util.ArrayList;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
public class demo extends javax.swing.JFrame {

    DefaultTableModel model;
    
  
    public demo() {
        initComponents();
        tabloYenileme();
       this.setLocationRelativeTo(null);
    }

    public ArrayList<Market> getProducts() throws SQLException{
    Connection connection= null;
    DbHelper dbHelper =new DbHelper();
    Statement statement = null;
    ResultSet  resultSet;
    ArrayList <Market> urunler =null;
    
    try{
    connection = dbHelper.getConnection();
    statement = connection.createStatement();
    resultSet = statement.executeQuery("select * from urunler order by urun_id ");
    urunler = new ArrayList<Market>();
    while(resultSet.next()){
        urunler.add(new Market(
        resultSet.getString("urun_adi"),
        resultSet.getInt("urun_id"),
        resultSet.getString("urun_uretici"),
        resultSet.getFloat("urun_fiyati")
                
        ));
    }
    } catch(SQLException exception){
    dbHelper.showErrorMessage(exception);

    }finally{
    statement.close();
    connection.close();
    }
    return urunler;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUrunler = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        lblUrunAdi = new javax.swing.JLabel();
        lblUrunId = new javax.swing.JLabel();
        lblUrunUretici = new javax.swing.JLabel();
        lblUrunFiyati = new javax.swing.JLabel();
        tbxUrunAdi = new javax.swing.JTextField();
        tbxUrunId = new javax.swing.JTextField();
        tbxUrunUretici = new javax.swing.JTextField();
        tbxUrunFiyati = new javax.swing.JTextField();
        btnEkle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        btnGuncelle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        tblUrunler.setAutoCreateRowSorter(true);
        tblUrunler.setBackground(new java.awt.Color(255, 255, 153));
        tblUrunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ürün adı", "ürün ID", "ürün üreticisi", "ürün fiyatı"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblUrunler.setGridColor(new java.awt.Color(204, 204, 255));
        tblUrunler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUrunlerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUrunler);

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblSearch.setText("ARANACAK İFADE:");

        lblUrunAdi.setText("Ürün Adı:");

        lblUrunId.setText("Ürün ID:");

        lblUrunUretici.setText("Ürün Üreticisi:");

        lblUrunFiyati.setText("Ürün Fiyatı:");

        tbxUrunFiyati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxUrunFiyatiActionPerformed(evt);
            }
        });

        btnEkle.setBackground(new java.awt.Color(0, 255, 51));
        btnEkle.setText("EKLE");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        btnSil.setBackground(new java.awt.Color(255, 0, 0));
        btnSil.setText("SİL");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnGuncelle.setForeground(new java.awt.Color(0, 153, 153));
        btnGuncelle.setText("GÜNCELLE");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUrunId))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbxUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbxUrunId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnGuncelle))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUrunUretici)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tbxUrunUretici, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUrunFiyati)
                                        .addGap(51, 51, 51)
                                        .addComponent(tbxUrunFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnSil)))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUrunAdi)
                    .addComponent(lblUrunUretici)
                    .addComponent(tbxUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxUrunUretici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxUrunId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUrunFiyati)
                    .addComponent(tbxUrunFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUrunId))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEkle)
                    .addComponent(btnSil)
                    .addComponent(btnGuncelle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
         String searchKey= txtSearch.getText();
        TableRowSorter<DefaultTableModel> tableRowSorter= new TableRowSorter<DefaultTableModel>(model);
        tblUrunler.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        Connection connection= null;
        DbHelper dbHelper =new DbHelper();
        // Select, Update, Delete gibi işlemleri çalıştırır
        PreparedStatement statement =null;
        
        try{
            //bağlantı oluştur
        connection =dbHelper.getConnection();
        //Veri ekleme işlemi ? = kullanıcıdan isteme
        String sql ="insert into urunler values(?,?,?,?)";
        //
        statement = connection.prepareStatement(sql);
        statement.setString(1,tbxUrunAdi.getText());
        statement.setInt(2,Integer.valueOf(tbxUrunId.getText()));
        statement.setString(3,tbxUrunUretici.getText());
        statement.setFloat(4,Integer.valueOf(tbxUrunFiyati.getText()));
        int result = statement.executeUpdate();
        tabloYenileme();
        
        }
        catch(SQLException exception){
            dbHelper.showErrorMessage(exception);
        } finally{
            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }    
        }       
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        Connection connection= null;
        DbHelper dbHelper =new DbHelper();
        // Select, Update, Delete gibi işlemleri çalıştırır
        PreparedStatement statement =null;
            
        try {
         //bağlantı oluşturdum
        connection =dbHelper.getConnection();
        //veritabanında ne yapmayı istediğimizi söylüyoruz, sorgu
        statement = connection.prepareStatement("DELETE FROM Urunler WHERE urun_ID=?");
       
                
        //burada da veriyi gönderiyoruz
        statement.setInt(1,Integer.parseInt(tbxUrunId.getText()));
        statement.execute();
        lblMessage.setText("Silme işlemi başarılı");
        tabloYenileme();}
                       
        catch (Exception e) {
            e.printStackTrace();
        }finally {
            try {   
                statement.close();
                connection.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }   
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
       DefaultTableModel model = new DefaultTableModel();
         Connection connection= null;
        DbHelper dbHelper =new DbHelper();
        // Select, Update, Delete gibi işlemleri çalıştırır
        PreparedStatement statement =null;
   
        try {
             
            connection =dbHelper.getConnection();
            
            String sql = "UPDATE Urunler SET urun_adi=?, urun_uretici=?, urun_fiyati =? WHERE  urun_id=?";
          
            statement = connection.prepareStatement(sql);
            
           statement.setString(1, tbxUrunAdi.getText());
            statement.setString(2, tbxUrunUretici.getText());
            statement.setFloat(3,Float.parseFloat(tbxUrunFiyati.getText()));
            statement.setInt(4, Integer.valueOf(tbxUrunId.getText()));
             
         statement.executeUpdate();
        tabloYenileme();
       
          lblMessage.setText("Güncelleme işlemi başarılı");

        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnGuncelleActionPerformed

    private void tblUrunlerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUrunlerMouseClicked
        model=(DefaultTableModel) tblUrunler.getModel();
      int SelectedRows=tblUrunler.getSelectedRow();
      
      tbxUrunAdi.setText(model.getValueAt(SelectedRows, 0).toString());
      tbxUrunId.setText(model.getValueAt(SelectedRows, 1).toString());
      tbxUrunUretici.setText(model.getValueAt(SelectedRows, 2).toString());
      tbxUrunFiyati.setText(model.getValueAt(SelectedRows, 3).toString());
    }//GEN-LAST:event_tblUrunlerMouseClicked

    private void tbxUrunFiyatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxUrunFiyatiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxUrunFiyatiActionPerformed
    
    public void tabloYenileme(){
      
      model=(DefaultTableModel) tblUrunler.getModel();
      model.setRowCount(0);
        try {
            ArrayList<Market> urunler =getProducts();
            for(Market market: urunler){
            Object[] rows = {market.getUrunAdi(), 
                market.getUrunID(),
                market.getUrunUretici(),
                market.getUrunFiyat()};
            
            //diziyi rowa ekledim
            model.addRow(rows);
            }
        } catch (SQLException ex) {
        }
    
    }
    
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnSil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblUrunAdi;
    private javax.swing.JLabel lblUrunFiyati;
    private javax.swing.JLabel lblUrunId;
    private javax.swing.JLabel lblUrunUretici;
    private javax.swing.JTable tblUrunler;
    private javax.swing.JTextField tbxUrunAdi;
    private javax.swing.JTextField tbxUrunFiyati;
    private javax.swing.JTextField tbxUrunId;
    private javax.swing.JTextField tbxUrunUretici;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
